### ISSUE TITLE
Any reason to require Feature Level 12_0?

### ISSUE THREAD

**Issue by alessiot89** [TheRealMJP/DeferredTexturing#1]
It actually works pretty well on AMD GCN Gen1 (tested on R9 280, which is actually a re-branded HD7950 at higher clock speed). Of course I modified the code to require FL 11_1. It does not run on Haswell (FL 11_1 too).
The first GPU is like all other FL 12_0 AMD GPUs (GCN Gen2 and beyond) except for tiled resources (tier 1 instead of tier 2), while hasswell does not support tiled resources at all (31-bit virtual address pain) and it is a tier 1 in resource binding (so no real bindless capabilities).
Maybe I just ignoring something, I did not deeply check the code now....

**Comment by TheRealMJP** [comment]
I had mistakenly thought that GCN1 was FL 12_0, but I was clearly wrong! When I get a chance, I will change the code to require FL11_1 with tier 2 resource binding. Thanks for pointing it out, and testing it on your hardware!

**Comment by TheRealMJP** [comment]
I pushed a fix for this: https://github.com/TheRealMJP/DeferredTexturing/commit/f8edb54454d21f5d1c0224cd4403ca0e3551ebde
