### ISSUE TITLE
Question about FP16Scale

### ISSUE THREAD

**Issue by omd24** [TheRealMJP/DeferredTexturing#13]
The `FP16Scale` in SF12_Math.h is described as 

> Scale factor used for storing physical light units in fp16 floats

I thought this might be a 32bit to 16bit conversion but that doesn't seem right, right? it is only applied when reading the model data (in Model.cpp) when storing spotlights intensity and then reapplied when doing exposure. I did a quick search on internet but haven't found anything about this specific value in literature. Is this a scene-specific constant based on max light value (e.g. sun brightness)? Or is it a rule-of-thumb value that works in most scenarios?

**Comment by TheRealMJP** [comment]
Hey there! I agree that comment could explain things better and be more helpful! The idea for that came from this blog post by Nathan Reed: [https://www.reedbeta.com/blog/artist-friendly-hdr-with-exposure-values/#fitting-into-half-float](https://www.reedbeta.com/blog/artist-friendly-hdr-with-exposure-values/#fitting-into-half-float)

Basically the maximum range of an fp16 value is insufficient for rendering with physical sunlight values, and so the scale factor effectively "slides" the fp16 range such that it can now fit reflected sunlight. Basically you scale the lighting input values downward, then later on when you're calculating exposure/tone-mapping/etc. you apply the inverse of that scale factor to get things back to the normal range.

**Comment by omd24** [comment]
Thanks for the info. So the current scale factor (2^-10) corresponds to the 10EV shift mentioned by Nathan Reed or is it just an arbitrary value?

**Comment by TheRealMJP** [comment]
Yup, an "EV" is basically a log2 "stop" in camera terminology, So 10 EV == 2^10, and -10 EV == 2^-10.

**Comment by omd24** [comment]
Oh, I see. I didn't know EVs are base-2 🙈. Now that makes perfect sense. Thanks again for the clarification and for this great repository 🙇
