### ISSUE TITLE
Running Crash that Init Picking StructedBuffer

### ISSUE THREAD

**Issue by DudeRenderer** [TheRealMJP/DeferredTexturing#14]
- File: GraphcsTypes.cpp:279
	-  ![image](https://github.com/TheRealMJP/DeferredTexturing/assets/33353769/15cd4b08-6d3b-4dbb-8488-2c7d913d7a8b)
- CallStack 
>  	KernelBase.dll!00007ffc7b5a536c()	Unknown
 	DXGIDebug.dll!00007ffc6bb63059()	Unknown
 	d3d12SDKLayers.dll!00007ffb43f8fcd8()	Unknown
 	d3d12SDKLayers.dll!00007ffb43eb4b2a()	Unknown
 	d3d12SDKLayers.dll!00007ffb43eb49e3()	Unknown
 	d3d12SDKLayers.dll!00007ffb43ee3976()	Unknown
 	d3d12SDKLayers.dll!00007ffb43ed8cf7()	Unknown
 	d3d12SDKLayers.dll!00007ffb43ec393d()	Unknown
>	BindlessDeferred_2019.exe!SampleFramework12::Buffer::Initialize(unsigned __int64 size, unsigned __int64 alignment, unsigned int dynamic, unsigned int cpuAccessible, unsigned int allowUAV, const void * initData, D3D12_RESOURCE_STATES initialState, ID3D12Heap * heap, unsigned __int64 heapOffset, const wchar_t * name) Line 279	C++
 	BindlessDeferred_2019.exe!SampleFramework12::StructuredBuffer::Initialize(const SampleFramework12::StructuredBufferInit & init) Line 510	C++
 	BindlessDeferred_2019.exe!BindlessDeferred::Initialize() Line 374	C++
 	BindlessDeferred_2019.exe!SampleFramework12::App::Initialize_Internal() Line 201	C++
 	BindlessDeferred_2019.exe!SampleFramework12::App::Run() Line 62	C++
 	BindlessDeferred_2019.exe!wWinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, wchar_t * lpCmdLine, int nCmdShow) Line 2431	C++
 	[External Code]	
  
- Output Message
> D3D12 WARNING: ID3D12Device::CreateCommittedResource: Ignoring InitialState D3D12_RESOURCE_STATE_GENERIC_READ. Buffers are effectively created in state D3D12_RESOURCE_STATE_COMMON. [ STATE_CREATION WARNING #1328: CREATERESOURCE_STATE_IGNORED]
D3D12: **BREAK** enabled for the previous message, which was: [ WARNING STATE_CREATION #1328: CREATERESOURCE_STATE_IGNORED ]
Exception thrown at 0x00007FFC7B5A536C (KernelBase.dll) in BindlessDeferred_2019.exe: 0x0000087A (parameters: 0x0000000000000002, 0x000000A1B091D350, 0x000000A1B091F120).
Unhandled exception at 0x00007FFC7B5A536C (KernelBase.dll) in BindlessDeferred_2019.exe: 0x0000087A (parameters: 0x0000000000000002, 0x000000A1B091D350, 0x000000A1B091F120).

**Comment by TheRealMJP** [comment]
Hey, thanks for reporting this. That's a new warning that was added in later versions of the debug layer which is why it's just popping up now. I'll make a quick commit to fix this.
