### ISSUE TITLE
DirectX Error: The GPU device instance has been suspended

### ISSUE THREAD

**Issue by Nolram12345** [TheRealMJP/DeferredTexturing#17]
Hello! I was trying to run the sample on my computer, however when starting the pre-built executable I get the following error:
![image](https://github.com/TheRealMJP/DeferredTexturing/assets/37701550/a41d7ec4-f720-4f82-84e0-5fea1f326698)

I'm running this on an RTX4080 with NVIDIA GR Driver Version 551.52 - I tried recompiling it in VS2022, but I was getting errors with it due to me using a newer version of VS since the project seems to have been compiled with VS2015.

**Comment by TheRealMJP** [comment]
Hey there! I just pushed a VS 2022 version of the solution and project if you want to try building that indead, it's called BindlessDeferred_2022.sln. Hopefully that should work for you. That pre-compiled binary is indeed quite out of date...I can also see if I can push a new release.

**Comment by Nolram12345** [comment]
Thank you very much! A new release would be good to have I believe, but I think even just having a VS2022 solution should hopefully help in figuring this issue out. Has anybody else encountered it before at all? Since I don't think it's an *actual* hardware incompatibility since an RTX4080 should be compatible with near any API feature out right now.

**Comment by TheRealMJP** [comment]
No I'm not aware of this happening for myself or anyone else. That said, I've made numerous changes over the years since I put up that pre-compiled binary, which include debug layer fixes and even switching shader compilers. So it wouldn't surprise be if the initial version had a bug or some other weirdness that is no longer present.

**Comment by Nolram12345** [comment]
Update - after recompiling it myself the error seems to have gone away. Thanks!
