### ISSUE TITLE
Exception thrown by SetComputeRootDescriptorTable call in RenderDeferred() due to invalid resource state (occurs only in the Debug build)

### ISSUE THREAD

**Issue by rskryptik61636** [TheRealMJP/DeferredTexturing#3]
An exception is thrown at the following call in the RenderDeferred() method in the Debug build:
cmdList->SetComputeRootDescriptorTable(Deferred_Descriptors, tableStart.GPUHandle);

The error message output by the DX debug layer is as follows:
D3D12 ERROR: CCommandList::SetComputeRootDescriptorTable: Resource state (0xA0: D3D12_RESOURCE_STATE_DEPTH_READ|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE) of resource (0x000001A4B11975D0:'Unnamed ID3D12Resource Object') (subresource: 0) is invalid for use as a NON_PIXEL_SHADER_RESOURCE.  Expected State Bits (all): 0x40: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE, Actual State: 0xA0: D3D12_RESOURCE_STATE_DEPTH_READ|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE, Missing State: 0x40: D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE. This validation is being enforced at bind during command list recording because the descriptor for this resource in the root signature is declared as DATA_STATIC_WHILE_SET_AT_EXECUTE. [ EXECUTION ERROR #538: INVALID_SUBRESOURCE_STATE]

What's odd is that the only resource that is ever in a state of 'D3D12_RESOURCE_STATE_DEPTH_READ|D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE' is the depth buffer and that is transitioned to 'D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE | D3D12_RESOURCE_STATE_DEPTH_READ' before the call to SetComputeRootDescriptorTable. Not sure why the runtime is throwing this error, maybe its some other resource?

I get the same error if I create a WARP device so I don't think it might be a driver issue.

My system config is as follows:
CPU: Intel i7-4770k
GPU: NVIDIA GeForce GTX 1060 6 GB
RAM: 8 GB
Driver version: 375.70 (Release date: 10/27/2016)

**Comment by TheRealMJP** [comment]
The resource it's complaining about is actually the shadow map depth buffer, which indeed the wrong state. I have a fix for this issue, but there's a few more new warnings that I need to fix.  The demo app used to run clean with the validation layer, but one of the recent Windows updates must have brought a new version of the validator that's catching more issues than the previous version.
