### ISSUE TITLE
CustomBuildEvent attempting to copy non-existent dxcompiler.dll causes the build to fail

### ISSUE THREAD

**Issue by rskryptik61636** [TheRealMJP/DeferredTexturing#7]
The following entry in BindlessDeferred.vcxproj attempts to copy the nonexistent dxcompiler.dll from the ..\Externals\DXCompiler\Bin folder to the output folder which causes the build to fail. Removing the offending entry fixes the issue.

https://github.com/TheRealMJP/DeferredTexturing/blob/7767a72624519181b194bf62c6a4a361a0390f81/BindlessDeferred/BindlessDeferred.vcxproj#L231-L235

**Comment by TheRealMJP** [comment]
Whoops, sorry about that! I forgot to fix that step so that it doesn't fail when dxcompiler.dll isn't present. Thanks for letting me know!
