### ISSUE TITLE
Roughness maps not being loaded

### ISSUE THREAD

**Issue by rskryptik61636** [TheRealMJP/DeferredTexturing#8]
I don't know if it's just me but I noticed that the roughness maps weren't being loaded. The model didn't seem to have any textures of type aiTextureType_SHININESS. This is on the latest version of the master branch with VS2017.

https://github.com/TheRealMJP/DeferredTexturing/blob/fe52746f13fc3762abdb53d9d2272ffcafd871eb/SampleFramework12/v1.01/Graphics/Model.cpp#L499-L500

**Comment by TheRealMJP** [comment]
Hey there, thanks for pointing this out! I swear that the roughness maps worked at some point...I wonder if they broke when I upgraded to a newer version of Assimp. I'll take a look at this when I have a few minutes to spare.

**Comment by rskryptik61636** [comment]
I worked around this creating a string array which contains the names of all the roughness maps in the correct order so that they line up with the rest of the maps. I committed [this](https://github.com/rskryptik61636/DeferredTexturing/commit/3b3a33e11c131d5efdf216fcdfaa5d2a8335cf55) into my fork of the project. See the changes to Model.cpp.

**Comment by TheRealMJP** [comment]
Yeah, that works. I think I may just copy that into the master branch, since that will probably be much quicker than debugging assimp. 😄
